# Generated by Django 4.2.13 on 2024-05-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='total_links',
            field=models.IntegerField(default=0),
        ),
    ]
